
dubbo:
  application:
    name: dubbo-hystrix-demo
  registry:
    id: my-registry
    address: zookeeper://localhost:2181?client=curator
  qosEnable: false

spring:
  aop:
    proxyTargetClass: true
